[package]
name = "boss"
description = "◇ The boss of package management."
version = "0.6.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.7", features = ["cargo"] }
cliclack = "0.2.5"
console = "0.15.8"
log = "0.4.22"
simplelog = "0.12.2"
strp = "1.1.2"
