[package]
name = "boss"
version = "0.4.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
cliclack = "0.2.5"
console = "0.15.8"
log = "0.4.22"
simplelog = "0.12.2"
strp = "1.1.2"
